"""Adding is_admin flag

Revision ID: 48cbb352369b
Revises: eca7934bfed8
Create Date: 2019-10-10 00:14:30.417615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48cbb352369b'
down_revision = 'eca7934bfed8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.execute('UPDATE public."user" SET is_admin = false')
    op.alter_column('user', 'is_admin', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin')
    # ### end Alembic commands ###
