"""Changing User password name and using hybrid_property

Revision ID: 52ed141d14e4
Revises: 48cbb352369b
Create Date: 2019-10-11 13:08:58.136058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52ed141d14e4'
down_revision = '48cbb352369b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('_password', sa.String(length=128), nullable=False))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.drop_column('user', '_password')
    # ### end Alembic commands ###
