"""Adding surname to Author model

Revision ID: 535e0e8f006f
Revises: 91be649172ef
Create Date: 2019-11-15 15:35:36.796883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '535e0e8f006f'
down_revision = '91be649172ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('surname', sa.String(length=80), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authors', 'surname')
    # ### end Alembic commands ###
