"""Name and Surname now are nullable

Revision ID: eca7934bfed8
Revises: 6a2c9c5ef514
Create Date: 2019-10-10 00:10:14.024345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eca7934bfed8'
down_revision = '6a2c9c5ef514'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'name', existing_type=sa.VARCHAR(length=80), nullable=True)
    op.alter_column(
        'user', 'surname', existing_type=sa.VARCHAR(length=120), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'user', 'surname', existing_type=sa.VARCHAR(length=120), nullable=False
    )
    op.alter_column('user', 'name', existing_type=sa.VARCHAR(length=80), nullable=False)
    # ### end Alembic commands ###
